#!/usr/bin/env bash
# configure my domain zone so that the subdomain www points to load balancer

func()
{

    for sub in 'www' '404-lb-01' '404-web-01' '404-web-01'
    do
	sub=$sub
	fqdn=$sub.$1
	dig "$fqdn" | grep "$fqdn" | tail -n 1 | \
awk '
{
{split($1, a, ".")}
}
{
printf "The subdomain %s is a %s record and points to %s\n",a[1],$4,$5
}
'
    done

}
func "$1"
