#!/usr/bin/env bash
# install load balancer with round robin
apt-get update
apt-get install -y software-properties-common
yes enter | add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update && apt-get upgrade -y
apt-get install -y haproxy=1.8.\*
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.copy
echo -e "\nfrontend http_front\n\tbind *:80\n\tstats uri /haproxy?stats\n\tdefault_backend http_back" >> /etc/haproxy/haproxy.cfg
echo -e "\nbackend http_back\n\tbalance roundrobin\n\tserver 404-web-01 34.73.47.85:80 check\n\tserver 404-web-02 34.73.31.23:80 check" >> /etc/haproxy/haproxy.cfg
sudo service rsyslog restart
service haproxy restart
