#!/usr/bin/env bash
# loops from 1 to 10 and display multiple strings

i=0
while [ $i -lt 10 ]; do
      if [ $i -eq 3 ]
      then
	echo "bad luck"
      elif [ $i -eq 7 ]
      then
	echo "good luck"
      else
	echo "codingschool School"
      fi
      i=$((i+1))
done
