#!/usr/bin/env bash
# display 12 hours and 59 minutes

i=0
j=1
while [ $i -ne 13 ]; do
     echo "Hour: $i"
     i=$((i+1))
     while [ $j -ne 60 ]; do
     	   echo $j
	   j=$((j+1))
     done
     j=1
done
