#!/usr/bin/env bash
# Config a Ubuntu server to:
# localhost resolves to 127.0.0.2
# facebook resolves to 8.8.8.8

cp /etc/hosts ~/temp
sed -i s/127.0.0.1/127.0.0.2/ ~/temp
echo "8.8.8.8 facebook.com" >> ~/temp
cp -f ~/temp /etc/hosts
